"""
Document intelligence pipeline:
  1. extract_text() — try native text extraction (PyMuPDF) first; fall back
     to OCR (pytesseract) only if the page has no extractable text layer.
     Also handles plain image files directly.
  2. extract_structured_fields() — prompts the LLM to return ONLY JSON
     matching a strict schema for the document type, validates the result,
     and retries once if the schema doesn't match.

This mirrors how a real derivatives-ops pipeline would ingest a mix of
native PDFs (trade confirmations generated by internal systems) and
scanned/faxed documents (older ISDA paperwork, broker confirms) into one
consistent structured-record pipeline.
"""

import json
import os
import fitz  # PyMuPDF
import pytesseract
from PIL import Image
from src.llm import call_llm

SCHEMAS = {
    "trade_confirmation": {
        "trade_date": "string YYYY-MM-DD",
        "counterparty": "string",
        "instrument": "string",
        "notional_amount": "number (USD)",
        "settlement_date": "string YYYY-MM-DD",
    },
    "isda_agreement": {
        "party_a": "string",
        "party_b": "string",
        "agreement_date": "string YYYY-MM-DD",
        "governing_law": "string",
        "threshold_amount": "number (USD)",
    },
    "options_chain_row": {
        "underlying": "string ticker",
        "expiration": "string YYYY-MM-DD",
        "rows": "array of {strike, type, bid, ask, volume}",
    },
}

_EXTRACTION_SYSTEM_PROMPT = """You are a document intelligence agent for a
derivatives operations team. You are given raw text (possibly OCR'd, so
expect minor noise) and a target JSON schema. Extract ONLY the fields in
the schema, using null for anything not present in the text. Output ONLY
valid JSON matching the schema — no prose, no markdown fences."""

def extract_text(path: str) -> tuple[str, str]:
    """
    Returns (text, method) where method is 'native' or 'ocr'.
    PDFs: try native text extraction per page; if a page has no text layer,
    render it to an image and OCR it instead.
    Images: OCR directly.
    """
    ext = os.path.splitext(path)[1].lower()

    if ext in (".png", ".jpg", ".jpeg", ".tiff", ".bmp"):
        text = pytesseract.image_to_string(Image.open(path))
        return text, "ocr"

    if ext == ".pdf":
        doc = fitz.open(path)
        all_text = []
        method = "native"
        for page in doc:
            page_text = page.get_text().strip()
            if page_text:
                all_text.append(page_text)
            else:
                # No text layer on this page — fall back to OCR
                pix = page.get_pixmap(dpi=200)
                img_path = path + f".page{page.number}.png"
                pix.save(img_path)
                ocr_text = pytesseract.image_to_string(Image.open(img_path))
                os.remove(img_path)
                all_text.append(ocr_text)
                method = "ocr"
        doc.close()
        return "\n".join(all_text), method

    raise ValueError(f"Unsupported file type: {ext}")


def extract_structured_fields(text: str, schema_name: str, max_retries: int = 1) -> dict:
    if schema_name not in SCHEMAS:
        raise ValueError(f"Unknown schema: {schema_name}")
    schema = SCHEMAS[schema_name]

    user_prompt = (
        f"TARGET SCHEMA:\n{json.dumps(schema, indent=2)}\n\n"
        f"DOCUMENT TEXT:\n{text}\n\n"
        "Extract the fields as JSON."
    )

    attempt = 0
    while attempt <= max_retries:
        raw = call_llm(_EXTRACTION_SYSTEM_PROMPT, user_prompt, role="extraction")
        try:
            result = json.loads(raw)
            missing_keys = set(schema.keys()) - set(result.keys())
            if not missing_keys:
                result["_extraction_valid"] = True
                return result
        except json.JSONDecodeError:
            pass
        attempt += 1
        user_prompt += "\n\nYour last output was invalid. Return ONLY valid JSON matching the schema exactly."

    return {"_extraction_valid": False, "_raw_output": raw, "_schema": schema_name}


def process_document(path: str, schema_name: str) -> dict:
    text, method = extract_text(path)
    fields = extract_structured_fields(text, schema_name)
    return {
        "source_file": os.path.basename(path),
        "extraction_method": method,
        "schema": schema_name,
        "fields": fields,
        "raw_text_preview": text[:300],
    }


if __name__ == "__main__":
    import sys
    from src.document_intelligence.generate_samples import OUT_DIR

    targets = [
        ("trade_confirmation_sample.pdf", "trade_confirmation"),
        ("isda_agreement_excerpt.pdf", "isda_agreement"),
        ("options_chain_scanned.png", "options_chain_row"),
    ]
    for filename, schema in targets:
        path = os.path.join(OUT_DIR, filename)
        if not os.path.exists(path):
            print(f"Missing sample: {path} — run generate_samples.py first")
            sys.exit(1)
        result = process_document(path, schema)
        print(f"\n=== {filename} (extraction method: {result['extraction_method']}) ===")
        print(json.dumps(result["fields"], indent=2))
